### ISSUE TITLE
Uninstall Tool Failing

### ISSUE THREAD

**Issue by leonpdawber** [codecrafting-io/asus-setup-tool#3]
Hi,

I've encountered an issue with this tool that seems to be preventing me from progressing beyond bloatware deletion, please find attached a screenshot of the issue I have encountered.

![kuCXY7hU1E](https://github.com/codecrafting-io/asus-setup-tool/assets/72570617/d82567a4-64ed-45db-b4f6-ec05c7551752)

It came up with with the below error, to which I press "OK" and the program continues before crashing, as per the above.

![image_2024-02-27_214205031](https://github.com/codecrafting-io/asus-setup-tool/assets/72570617/b72562de-e746-4d3c-9b46-668d0a330654)

I'm running setup.bat as administrator, on Windows 11 Pro 23H2.
Any ideas?

**Comment by codecrafting-io** [comment]
Hi, Sorry. This is indeed a problem from 0.5.0, if you haven't already downloaded and extracted the UninstallTool. I will fix this in 0.6.0, in the meantime you can try 0.4.0. The error windows that came up are related to a bad uninstall of AuraSync, since no files were removed, so the tool thinks AuraSync is still installed. The new version 0.6.0 will be released soon, but introduces some changes in the setup process that are not yet finished.

But until you read this maybe 0.6.0 was released, so you try this version

**Comment by codecrafting-io** [comment]
Just released version [v0.6.0](https://github.com/codecrafting-io/asus-setup-tool/releases/tag/v0.6.0). This error should be fixed. Note that the setup flow is different now, so pay attention to the questions.
